### PR TITLE
linux-raspberrypi: update to 5.10.46

### PR DESCRIPTION
**Pull request by MarkusVolk**
tested this kernel for some days and it seems to run well.

### CODE REVIEW

**Comment by dev-0x7C6** [comment]
RT flavor probably will fail after that change.

**Comment by MarkusVolk** [comment]
> RT flavor probably will fail after that change.

i'll check that tomorrow

**Comment by dev-0x7C6** [comment]
No worries, I'll fix that occasionally, thanks :)

**Comment by dev-0x7C6** [comment]
e52dce18a6f0f822c98fa648f44cbebd0657f33b looks like `patch-5.10.47-rt45.patch.gz` applies successfully on `5.10.46`, no compilation failures either.

**Pull request merged**
