### PR TITLE
vc4graphics.cfg: build DRM_VC4 as a module

### PR DESCRIPTION
**Pull request by MarkusVolk**
Somewhere inside the raspberry code this is expected to be built as a module.
Since i don't know better i assume that is for a reason. But if not at least this misleading error gets removed from the log:

You have a RaspberryPi, but the vc4 Module is not loaded! Set 'dtoverlay=vc4-kms-v3d' in /boot/config.txt and reboot.

### CODE REVIEW

**Comment by dev-0x7C6** [comment]
Is this sway output? Found something [there](https://github.com/swaywm/sway/blob/master/sway/main.c#L50) and it looks like checking for vc4 support by checking module list. Probably raspbian is using vc4 as module. I think this is some kind shortcut for developers and should be done properly by querying device.

Anyway I don't have any objections to make it as module. But I'm hoping that screen is early initialized.

**Comment by dev-0x7C6** [comment]
https://github.com/swaywm/sway/issues/6241

**Comment by dev-0x7C6** [comment]
@MarkusVolk You can try to apply this [patch](https://patch-diff.githubusercontent.com/raw/swaywm/sway/pull/6242.patch) on sway.

**Comment by MarkusVolk** [comment]
I've seen that your change already was accepted upstream. I'll build sway from current code

**Comment by MarkusVolk** [comment]
As expected the error message is gone after sway update

**Pull request closed without merging**
